### PR TITLE
Upgrade bs-platform and remove Js.Boolean usage as it was deprecated

### PR DESCRIPTION
**Pull request by fakenickels**

### CODE REVIEW

**Comment by Risto-Stevcev** [comment]
Thanks for the PR. Can you separate the code reformatting part into a separate commit called something like "reformat code" or "whitespace changes"?
It's hard to tell in the diffs what actually got changed vs whitespace changes

**Comment by fakenickels** [comment]
For sure! Gonna push soon

**Comment by Risto-Stevcev** [comment]
I added the whitespace changes. Can you run:
```bash
git rebase master
git checkout --theirs src/Verify.re
git checkout --theirs test/Test_Verify.re
```
on your branch and push it up?
it looks the deps in the `yarn.lock` file also changed, but `bs-platform` has no deps. It looks like it might be from mocha v5

**Comment by fakenickels** [comment]
Indeed the changes in `yarn.lock` are from mocha. I'm gonna try to reverse that here

**Comment by fakenickels** [comment]
I just realised I obliterated the boolean changes commit during rebase, gonna fix that also

**Comment by Risto-Stevcev** [comment]
I created a new pull request with your changes in it from this PR and rebased and merged it in. It's all your original commits and shows you as a contributor
Sorry for all the inconvenience on this one... I should've just used refmt from the start since it's an open source library, it was a bad decision on my part

**Comment by fakenickels** [comment]
Thank you @Risto-Stevcev ! Sorry for delaying on this

**Pull request closed without merging**
